---
# tasks file for apache
- name: Install required packages
  dnf:
    name: "{{item}}"
    state: present
  loop: "{{pkg_name}}"

- name: Start & Enable Services
  service:
    name: "{{item}}"
    state: started
    enabled: yes
  loop: "{{svc_name}}"

- name: Deploy index page
  copy:
    content: "This is my Web Page using roles"
    dest: /var/www/html/index.html

