---
- name: Play to create user with vault info
  hosts: all
  vars_files:
    - user_list.yml
    - vault.yml

  tasks:
    - name: Create groups
      group: 
         name: "{{item}}"
         state: present
      loop: "{{group_list}}"
         
    - name: Create dev users
      user:
         name: "{{item.name}}"
         state: present
         groups: devops
         password: "{{ dev_pass | password_hash('sha512') }}"
      loop: "{{users}}"
      when: 
        - item.job == "developer"
        - inventory_hostname in groups['dev'] or inventory_hostname in groups['test']

    - name: Create manager users
      user:
         name: "{{item.name}}"
         state: present
         groups: opsmgr
         password: "{{ mgr_pass | password_hash('sha512') }}"
      loop: "{{users}}"
      when: 
        - item.job == "manager"
        - inventory_hostname in groups['prod']

