---
- name: Play for setting up cron
  hosts: dev
  tasks:
    - name: Ensure a job that runs at 2 and 5 exists. Creates an entry like "0 5,2 * * ls -alh > /dev/null"
      ansible.builtin.cron:
        name: "check dirs"
        minute: "0"
        hour: "5,2"
        job: /bin/logger "TESTING"
        user: student
        state: absent
        cron_file: loggerfile

