---
- name: Playbook to use shell commands
  hosts: web
  gather_facts: no
  tasks:
    - name: Task to run command on target servers
      ansible.builtin.shell:
         cmd: cat /etc/shadow
      register: cmd_out

    - name: Print cmd output
      debug:
         msg: "OS Version of {{inventory_hostname}} is: {{cmd_out.stdout_lines}}"
