---
- name: Playbook to install HTTPD & Firewall
  hosts: prod
  gather_facts: no
  tasks:
    - name: Task to install HTTPD
      ansible.builtin.yum:
        name: httpd
        state: absent


    - name: Task to install firewall
      ansible.builtin.dnf:
        name: firewalld
        state: absent

    - name: Task to start httpd service
      ansible.builtin.service:
        name: httpd
        state: stopped
        enabled: no
      ignore_errors: yes


    - name: Task to start firewalld service
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Enable firewall for http
      ansible.posix.firewalld:
        service: http
        immediate: yes
        state: disaabled
        permanent: yes

#    - name: Create web page
#      copy:
#        content: "THIS IS PRACTISE WEB PAGE in host {{inventory_hostname}}\n"
#        dest: /var/www/html/index.html
