---
- name: Playbook to create User and Group
  hosts: prod
  gather_facts: no

  tasks:
  - name: Task to create group
    ansible.builtin.group:
       name: unixadm
       state: present
       gid: 33441

  - name: Task to create user
    ansible.builtin.user:
       name: unixmon
       comment: UnixMonuser
       uid: 220021
       group: unixadm    
